#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/spring_batch
#    username: club
#    password: club
#  batch:
#    jdbc:
#      initialize-schema: always
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: test
    password: test
  batch:
    jdbc:
      initialize-schema: always

